# Generated by Django 5.2.7 on 2025-11-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('false_positive_reduction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistsuggestion',
            name='false_positive',
        ),
        migrations.RemoveField(
            model_name='learningmodesession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='whitelistexport',
            name='session',
        ),
        migrations.DeleteModel(
            name='FalsePositiveDetection',
        ),
        migrations.DeleteModel(
            name='WhitelistSuggestion',
        ),
        migrations.DeleteModel(
            name='LearningModeSession',
        ),
        migrations.DeleteModel(
            name='WhitelistExport',
        ),
    ]
