# Generated by Django 5.2.7 on 2025-11-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('false_positive_reduction', '0002_remove_whitelistsuggestion_false_positive_and_more'),
        ('optimization_recs_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FalsePositiveDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=50)),
                ('false_positive_count', models.IntegerField(default=0)),
                ('legitimate_request_count', models.IntegerField(default=0)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('blocked_requests', models.JSONField(default=list)),
                ('request_patterns', models.JSONField(default=dict)),
                ('detection_method', models.CharField(choices=[('manual', 'Manual Detection'), ('learning', 'Learning Mode'), ('ai', 'AI Detection')], default='manual', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('analyzing', 'Analyzing'), ('whitelisted', 'Whitelisted'), ('resolved', 'Resolved')], default='detected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='false_positives', to='optimization_recs_module.ruleanalysissession')),
            ],
            options={
                'db_table': 'false_positive_detections',
            },
        ),
        migrations.CreateModel(
            name='LearningModeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('learning_duration_hours', models.IntegerField(default=24)),
                ('traffic_sample_size', models.IntegerField(default=1000)),
                ('normal_traffic_patterns', models.JSONField(default=dict)),
                ('baseline_metrics', models.JSONField(default=dict)),
                ('anomaly_thresholds', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active Learning'), ('completed', 'Learning Completed'), ('paused', 'Paused'), ('failed', 'Learning Failed')], default='active', max_length=20)),
                ('patterns_learned', models.IntegerField(default=0)),
                ('false_positive_predictions', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='optimization_recs_module.ruleanalysissession')),
            ],
            options={
                'db_table': 'learning_mode_sessions',
            },
        ),
        migrations.CreateModel(
            name='WhitelistExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_name', models.CharField(default='waf_whitelist.csv', max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('include_patterns', models.JSONField(default=list)),
                ('export_format', models.CharField(choices=[('csv', 'CSV Format'), ('json', 'JSON Format'), ('xml', 'XML Format')], default='csv', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_patterns', models.IntegerField(default=0)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_exports', to='optimization_recs_module.ruleanalysissession')),
            ],
            options={
                'db_table': 'whitelist_exports',
            },
        ),
        migrations.CreateModel(
            name='WhitelistSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('ip_whitelist', 'IP Address Whitelist'), ('user_agent_whitelist', 'User Agent Whitelist'), ('path_whitelist', 'Path Whitelist'), ('parameter_whitelist', 'Parameter Whitelist'), ('header_whitelist', 'Header Whitelist'), ('custom_pattern', 'Custom Pattern')], max_length=50)),
                ('pattern_description', models.TextField()),
                ('pattern_regex', models.TextField(blank=True, null=True)),
                ('pattern_conditions', models.JSONField(default=dict)),
                ('estimated_false_positive_reduction', models.FloatField(default=0.0)),
                ('security_risk_assessment', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('implementation_priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('false_positive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_suggestions', to='false_positive_reduction.falsepositivedetection')),
            ],
            options={
                'db_table': 'whitelist_suggestions',
            },
        ),
        migrations.AddIndex(
            model_name='falsepositivedetection',
            index=models.Index(fields=['rule_id', 'false_positive_rate'], name='false_posit_rule_id_f54dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='falsepositivedetection',
            index=models.Index(fields=['status'], name='false_posit_status_f44d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='falsepositivedetection',
            index=models.Index(fields=['detection_method'], name='false_posit_detecti_034135_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='falsepositivedetection',
            unique_together={('rule_id', 'session')},
        ),
        migrations.AddIndex(
            model_name='learningmodesession',
            index=models.Index(fields=['status'], name='learning_mo_status_b04d52_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmodesession',
            index=models.Index(fields=['started_at'], name='learning_mo_started_5f2ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='whitelistexport',
            index=models.Index(fields=['status'], name='whitelist_e_status_687288_idx'),
        ),
        migrations.AddIndex(
            model_name='whitelistexport',
            index=models.Index(fields=['created_at'], name='whitelist_e_created_137f06_idx'),
        ),
        migrations.AddIndex(
            model_name='whitelistsuggestion',
            index=models.Index(fields=['suggestion_type'], name='whitelist_s_suggest_6696a8_idx'),
        ),
        migrations.AddIndex(
            model_name='whitelistsuggestion',
            index=models.Index(fields=['status'], name='whitelist_s_status_9f6f74_idx'),
        ),
        migrations.AddIndex(
            model_name='whitelistsuggestion',
            index=models.Index(fields=['implementation_priority'], name='whitelist_s_impleme_1ca827_idx'),
        ),
    ]
